pub mod advisory;
pub mod cache;
pub mod ecosystem;
pub mod evaluator;
pub mod finding;
pub mod matcher;
pub mod intel;
pub mod osv;
pub mod osv_evaluator;
pub mod policy;
pub mod postinstall;
pub mod provenance;
pub mod resolver;

pub use advisory::{Advisory, Severity, ThreatClass};
pub use ecosystem::{Ecosystem, PackageRef};
pub use evaluator::{evaluate_all, EvaluatorRegistry};
pub use finding::{decide_action, Evaluator, Finding, FindingKind, FindingSeverity};
pub use matcher::{MatchResult, Verdict};
pub use policy::{Action, Policy};
